### PR TITLE
Add Navigation For Onboarding

### PR DESCRIPTION
**Pull request by brh55**
# Add Navigation For Onboarding
> Issue #84 

This allows the user to navigate between the configuration pages during onboard. Currently, it works as intended, but I would like to add a few tests on the navigation component. Since I'll be on vacation, I figure it would be a good idea to test it and make sure it doesn't cause any potential build or rendering issues.

PR Include:
- Reusable nav component for Onboarding
- Minor stylistic changes on Location
- Start of Category Page (in order to test navigation)
- Add A Site Title For Now - Hopdrops - "Live Can Releases for Your Loyal Fans"

image

image

> Note: This page isn't complete yet

image

## Testing
1. `cd /app`
2. `npm start -s`
3. Go to Browser:  `localhost:3000/settings/locations`
4. Select locations and hit the next button
5. An incomplete category page will render
6. Select `back` and you should return back to the locations view

### CODE REVIEW

**Comment by jasonwalsh** [comment]
I would update the text on the `/settings/locations` page from "Choose a Locations" to "Select locations" or something along those lines.

**Comment by jasonwalsh** [comment]
If a merchant only has one location should we still show them this page and automatically have that location checked?

**Comment by jasonwalsh** [comment]
@brh55 is this addressed? https://github.com/hopdrops/hopdrops/pull/85#issuecomment-524843167

If not, I'm fine with approving otherwise, but we should create a separate issue for future consideration.

**Comment by jasonwalsh** [comment]
Also; please, no merge commits (cc732f6)

**Comment by brh55** [comment]
> @brh55 is this addressed? [#85 (comment)](https://github.com/hopdrops/hopdrops/pull/85#issuecomment-524843167)
> 
> If not, I'm fine with approving otherwise, but we should create a separate issue for future consideration.

Not addressed in PR, I'll create a separate story for using our back end to render data which will include this check, but we will need to figure out hosting as well.

**Comment by jasonwalsh** [comment]
I am going to merge this since @AmillerSC has already tested this feature locally as well.

**Pull request merged**
