### PR TITLE
feat: add DynamoDB Merchant table in Terraform

### LINKED ISSUE #47: Create DynamoDB table for user accounts
The `redirect.py` lambda functions requires a DynamoDB table to persist user data.

### PR DESCRIPTION
**Pull request by jasonwalsh**
`aws_dynamodb_table` [documentation](https://www.terraform.io/docs/providers/aws/r/dynamodb_table.html).

This pull request includes a *very* minimal configuration for a DynamoDB table. I am open to discussing more about access patterns and read/write performance.

Closes #47

### CODE REVIEW

**Comment by brh55** [comment]
Do we want to address the schema in another PR?

**Comment by jasonwalsh** [comment]
@brh55, yes we can create another issue to define the schema.

**Comment by jasonwalsh** [comment]
@brh55 can you approve the review?

**Pull request merged**
