### PR TITLE
build: add Ansible playbook for sam deployments

### LINKED ISSUE #69: Create makefile for SAM
Consolidate 3 commands for infrastructure deployment into one

### PR DESCRIPTION
**Pull request by jasonwalsh**
### Purpose

This pull request introduces an [Ansible Playbook](https://docs.ansible.com/ansible/latest/user_guide/playbooks.html) for consolidating the three commands required to deploy an AWS lambda application in SAM to one command.

### Usage

To deploy the lambda application:

    $ ansible-playbook \
          -i localhost, playbook.yml \
          -e '{"parameter_overrides": ["ClientSecret=sandbox-sqXXXX"]}'

To destroy the lambda application:

    $ ansible-playbook -i localhost, playbook.yml --tags destroy

Closes #69

### CODE REVIEW

**Comment by brh55** [comment]
I'll be honest command is not particularly intuitive (esp the -e flag), despite it being a typical ansible abstraction. We should consider some further .py scripts later -- obviously not now.

**Comment by jasonwalsh** [comment]
There are two options here:

1. Create a `Makefile` with targets that invokes the Ansible playbook

2. Create a [`setup.py`](https://docs.python.org/3.7/distutils/extending.html#integrating-new-commands) script with a [`cmdcls`](https://docs.python.org/3.7/distutils/extending.html#integrating-new-commands) directive for custom commands: (e.g., `python setup.py deploy`)

/cc @brh55 @AmillerSC

**Comment by AmillerSC** [comment]
> There are two options here:
> 
> 1. Create a `Makefile` with targets that invokes the Ansible playbook
> 2. Create a [`setup.py`](https://docs.python.org/3.7/distutils/extending.html#integrating-new-commands) script with a [`cmdcls`](https://docs.python.org/3.7/distutils/extending.html#integrating-new-commands) directive for custom commands: (e.g., `python setup.py deploy`)
> 
> /cc @brh55 @AmillerSC

I have created issue #77 for this for future enhancement and referenced the two options. It is not currently a priority but can be addressed when time permits. I would not expect it to be looked at for a few weeks.

**Pull request merged**
